services:
  ollama:
    image: ollama/ollama
    container_name: ollama-container
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]


  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    image: fastapi-ollama-image:latest
    container_name: fastapi-ollama-container
    ports:
      - "8000:8000"
    depends_on:
      - ollama

    environment:
      - OLLAMA_HOST=http://ollama:11434

volumes:
  ollama-data:
